In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("data/house_prices_srilanka.csv")

In [6]:
df.head()

,district,area,perch,bedrooms,bathrooms,kitchen_area_sqft,parking_spots,has_garden,has_ac,water_supply,electricity,floors,year_built,price_lkr
0,Polonnaruwa,Polonnaruwa Central,14,5,4,112,2,False,False,Pipe-borne,Single phase,1,2022,16236332
1,Matale,Matale Central,26,7,5,250,2,True,False,Both,Single phase,3,1987,33907509
2,Mullaitivu,Mullaitivu Central,7,3,2,77,2,True,True,Well,Single phase,1,1988,5954312
3,Anuradhapura,New Town,2,2,2,39,1,True,True,Both,Three phase,2,2024,5177534
4,Batticaloa,Batticaloa Town,20,5,4,117,1,True,True,Well,Single phase,1,1995,20182409

In [7]:
df.shape

(20000, 14)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   district           20000 non-null  str
 1   area               20000 non-null  str
 2   perch              20000 non-null  int64
 3   bedrooms           20000 non-null  int64
 4   bathrooms          20000 non-null  int64
 5   kitchen_area_sqft  20000 non-null  int64
 6   parking_spots      20000 non-null  int64
 7   has_garden         20000 non-null  bool
 8   has_ac             20000 non-null  bool
 9   water_supply       20000 non-null  str
 10  electricity        20000 non-null  str
 11  floors             20000 non-null  int64
 12  year_built         20000 non-null  int64
 13  price_lkr          20000 non-null  int64
dtypes: bool(2), int64(8), str(4)
memory usage: 1.9 MB

In [9]:
df.describe()

,perch,bedrooms,bathrooms,kitchen_area_sqft,parking_spots,floors,year_built,price_lkr
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,2.000000e+04
mean,11.510500,3.901600,3.171650,113.718800,1.141100,1.557150,2004.926550,1.598142e+07
std,8.519719,1.839426,1.530883,69.801873,0.939167,0.628135,11.817353,1.338156e+07
min,2.000000,1.000000,1.000000,35.000000,0.000000,1.000000,1985.000000,1.500000e+06
25%,5.000000,2.000000,2.000000,53.000000,0.000000,1.000000,1995.000000,6.591047e+06
50%,10.000000,4.000000,3.000000,95.000000,1.000000,1.000000,2005.000000,1.206384e+07
75%,16.000000,5.000000,5.000000,161.000000,2.000000,2.000000,2015.000000,2.096723e+07
max,80.000000,7.000000,5.000000,250.000000,3.000000,3.000000,2025.000000,1.500321e+08

In [10]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, KFold, cross_val_score, GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestRegressor, HistGradientBoostingRegressor

from sklearn.metrics import(
    mean_absolute_error,
    mean_squared_error,
    r2_score,
)

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   district           20000 non-null  str
 1   area               20000 non-null  str
 2   perch              20000 non-null  int64
 3   bedrooms           20000 non-null  int64
 4   bathrooms          20000 non-null  int64
 5   kitchen_area_sqft  20000 non-null  int64
 6   parking_spots      20000 non-null  int64
 7   has_garden         20000 non-null  bool
 8   has_ac             20000 non-null  bool
 9   water_supply       20000 non-null  str
 10  electricity        20000 non-null  str
 11  floors             20000 non-null  int64
 12  year_built         20000 non-null  int64
 13  price_lkr          20000 non-null  int64
dtypes: bool(2), int64(8), str(4)
memory usage: 1.9 MB

In [12]:
df.dropna(inplace=True)

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   district           20000 non-null  str
 1   area               20000 non-null  str
 2   perch              20000 non-null  int64
 3   bedrooms           20000 non-null  int64
 4   bathrooms          20000 non-null  int64
 5   kitchen_area_sqft  20000 non-null  int64
 6   parking_spots      20000 non-null  int64
 7   has_garden         20000 non-null  bool
 8   has_ac             20000 non-null  bool
 9   water_supply       20000 non-null  str
 10  electricity        20000 non-null  str
 11  floors             20000 non-null  int64
 12  year_built         20000 non-null  int64
 13  price_lkr          20000 non-null  int64
dtypes: bool(2), int64(8), str(4)
memory usage: 1.9 MB

In [14]:
target_col = "price_lkr"
num_cols = df.select_dtypes(include=[np.number]).columns.tolist()
cat_cols = df.select_dtypes(include=["object"]).columns.tolist()

print("Numerical columns: - house_price_project.ipynb:5", num_cols)
print("Categorical columns: - house_price_project.ipynb:6", cat_cols)
print("Target column: - house_price_project.ipynb:7", target_col)

Numerical columns: - house_price_project.ipynb:5 ['perch', 'bedrooms', 'bathrooms', 'kitchen_area_sqft', 'parking_spots', 'floors', 'year_built', 'price_lkr']
Categorical columns: - house_price_project.ipynb:6 ['district', 'area', 'water_supply', 'electricity']
Target column: - house_price_project.ipynb:7 price_lkr

C:\Users\Kavindhya\AppData\Local\Temp\ipykernel_20796\3130270943.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include=["object"]).columns.tolist()

In [24]:
print("\nMissing values per column - house_price_project.ipynb:1")
print(df.isnull().sum())

Missing values per column - house_price_project.ipynb:1
district             0
area                 0
perch                0
bedrooms             0
bathrooms            0
kitchen_area_sqft    0
parking_spots        0
has_garden           0
has_ac               0
water_supply         0
electricity          0
floors               0
year_built           0
price_lkr            0
dtype: int64

In [26]:
for col in df.columns:
    print(df[col].value_counts().head(20))

district
Polonnaruwa     845
Batticaloa      837
Badulla         834
Gampaha         825
Colombo         818
Hambantota      814
Kegalle         810
Kurunegala      810
Kandy           809
Ampara          807
Monaragala      807
Jaffna          802
Kalutara        801
Mannar          801
Galle           801
Puttalam        799
Anuradhapura    790
Matale          788
Kilinochchi     788
Vavuniya        782
Name: count, dtype: int64
area
Polonnaruwa Central     845
Kegalle Central         810
Ampara Central          807
Monaragala Central      807
Mannar Central          801
Puttalam Central        799
Matale Central          788
Kilinochchi Central     788
Vavuniya Central        782
Mullaitivu Central      781
Nuwara Eliya Central    765
Hambantota Town         297
Bandarawela             291
China Bay               288
Batticaloa Town         286
Badulla Town            281
Kallady                 280
Madawachchiya           273
Ambalantota             273
Eravur                  271
Name: count, dtype: int64
perch
2     1853
5     1267
7     1207
4     1200
6     1159
3     1130
8     1113
9     1050
10    1015
11     961
12     860
13     781
14     718
15     635
16     592
17     531
18     465
19     432
20     356
21     311
Name: count, dtype: int64
bedrooms
3    3581
2    3427
5    3059
4    3005
6    2968
1    2068
7    1892
Name: count, dtype: int64
bathrooms
5    6094
1    4113
2    3580
3    3162
4    3051
Name: count, dtype: int64
kitchen_area_sqft
35     2288
250    1862
38      195
52      181
44      173
49      169
51      166
41      165
50      163
45      160
43      153
58      152
40      151
47      151
39      150
37      148
46      147
53      145
71      144
74      142
Name: count, dtype: int64
parking_spots
1    7956
0    5610
2    4436
3    1998
Name: count, dtype: int64
has_garden
True     11124
False     8876
Name: count, dtype: int64
has_ac
False    10711
True      9289
Name: count, dtype: int64
water_supply
Both          6767
Pipe-borne    6697
Well          6536
Name: count, dtype: int64
electricity
Single phase    10037
Three phase      9963
Name: count, dtype: int64
floors
1    10335
2     8187
3     1478
Name: count, dtype: int64
year_built
1999    538
2000    529
2021    528
2023    522
2003    517
1990    516
1997    514
1991    513
1987    502
2005    502
2010    499
1995    498
2002    498
2006    497
1993    491
2007    489
1998    489
2017    488
1985    488
1989    486
Name: count, dtype: int64
price_lkr
1500000     5
19216537    2
44615320    2
23172254    2
11412125    2
4461428     2
16236332    1
33907509    1
5954312     1
5177534     1
20182409    1
23615818    1
38172705    1
4234524     1
10184076    1
8733878     1
37541652    1
32837599    1
26636331    1
3877762     1
Name: count, dtype: int64